export { ReactComponent as LogoImage } from './logo.svg'
export { ReactComponent as CalendarIcon } from './calendar.svg'
export { ReactComponent as Alarm } from './alarm.svg'
export { ReactComponent as Profile } from './profile.svg'
export { ReactComponent as Heartrate } from './heartrate.svg'
export { ReactComponent as Step } from './step.svg'
export { ReactComponent as DownArrow } from './downArrow.svg'
